### ISSUE TITLE
[Question] TPromise Example

### ISSUE THREAD

**Issue by savasozer** [landelare/ue5coro#20] opened 2023-11-21 16:05 UTC
First of all, thank you for such an excellent plugin. As a C# guy, I was very happy to find this plugin. It gives me the comfort of C#. But although I could do many things I wanted, I could not see a class that I could use like TaskCompletionSource<T> in C#. I found the TPromise class as the closest alternative. But I think this works a little differently than that.

A 3rd party SDK I use returns the results of API calls via events. I want to wait for these results with TPromise and have my function continue where it left off after the event is called.

1-Is TPromise suitable for this job?
2-An example of usage for this would be great.

Thanks

**Comment by landelare** [comment] 2023-11-21 16:52
There's no direct TCS equivalent. You could use a FAwaitableEvent for custom/arbitrary wait conditions, or if this is an Unreal delegate, you can co_await that directly. TPromise from the engine has some design issues and as such I wouldn't recommend its use, but it is supported as much as Unreal allows.

Closing this, since it is not a bug.

**Closed by landelare** 2023-11-21 16:52 UTC
